fix(just): 🐛 fix just invocation on windows
Description: On windows, running just would pick up some unix specific recipes and return an error in the form of:
    error: Recipe `x` has unknown dependency `y`

Fix: Added missing [unix] headers to unix specific recipes.